_wandb:
    value:
        cli_version: 0.21.2
        e:
            mf29m8mfdxmrauzsonc66xqts3lf6c4j:
                codePath: cs336_basics/wandb_test.py
                codePathLocal: cs336_basics/wandb_test.py
                email: lzj1959797276@gmail.com
                executable: /Users/ziji/CS336LLM/assignment1-basics/.venv/bin/python
                git:
                    commit: 94e8fba42620fe703f3fcd157a4b2c5a59c88f70
                    remote: https://github.com/Tyler03118/cs336-llm-assignment1.git
                host: FlexHub.local
                os: macOS-26.3-arm64-arm-64bit
                program: /Users/ziji/CS336LLM/assignment1-basics/cs336_basics/wandb_test.py
                python: CPython 3.11.4
                root: /Users/ziji/CS336LLM/assignment1-basics
                startedAt: "2026-02-26T19:06:24.512192Z"
                writerId: mf29m8mfdxmrauzsonc66xqts3lf6c4j
        m: []
        python_version: 3.11.4
        t:
            "3":
                - 2
                - 16
            "4": 3.11.4
            "5": 0.21.2
            "12": 0.21.2
            "13": darwin-arm64
architecture:
    value: CNN
dataset:
    value: CIFAR-100
epochs:
    value: 10
learning_rate:
    value: 0.02
